on:
  issues:
    types: [opened, edited]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Automatically close issues that don't follow the issue template
        uses: josemauro/auto-close-issues@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "Hello @${issue.user.login}! :wave:\n\nThis issue is being automatically closed because as previously announced on our communication channels, the Kytos project will enter the 'shutdown' phase on May 31, 2021. After this date, only critical patches (security and core bug fixes) will be accepted, and the project will be in 'critical-only' mode for another six months (until November 30, 2021). This issue will be analysed and manually reopened by our team if classified as critical. For more information visit this [FAQ](https://kytos.io/faq/). We'll have eternal gratitude to the entire community of developers and users that made the project so far."
          closed-issues-label: "Waiting for review."
